# docker-compsoe file for testing networking with static IPs
services:
  # node0:
  #   environment:
  #     RUST_BACKTRACE: 1
  #     RUST_LOG: zilliqa=info
  #   container_name: zilliqanode0
  #   image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zq2:v0.5.3
  #   volumes:
  #     - "../zq2/zq2-infratest.toml:/config.toml"
  #   command:
  #     - 03ec029a940a2dd787f1c20419f82a37e6c0f0c38f05d11b21d12945d0c5bc3e
  #   ports:
  #     - "4201:4201"
  #     - "4202:4202"
  #     - "3333:3333/udp"
  #   networks:
  #     testnet:
  #       ipv4_address: 198.51.100.103

  dashboard:
    environment:
      WS_SECRET: mysecret
    container_name: dashboard
    build:
      context: ../ethstats-server
      dockerfile: Dockerfile
    image: zilstats-server:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    # Fast shutdown - Don't gracefully close open connections.
    stop_signal: SIGKILL
    networks:
      testnet:
        ipv4_address: 198.51.100.10

  client0:
    depends_on:
      - dashboard
      #- node0
    environment:
      RPC_HOST: zq2-devnet-validator-ase1-0-a6d2.zq2.dev #"198.51.100.103"
      RPC_PORT: "4202"
      LISTENING_PORT: "3333"
      INSTANCE_NAME: "zq2-devnet-validator-ase1-0-a6d2"
      CONTACT_DETAILS: "devops@zilliqa.com"
      WS_SERVER: "ws://198.51.100.10:3000"
      WS_SECRET: "mysecret"
      VERBOSITY: "2"
    container_name: client0
    build:
      context: .
      dockerfile: Dockerfile.zilliqa
    image: zilstats-client:latest
    networks:
      testnet:
        ipv4_address: 198.51.100.50

  client1:
    depends_on:
      - dashboard
      #- node0
    environment:
      RPC_HOST: zq2-devnet-validator-ase1-1-a6d2.zq2.dev #"198.51.100.103"
      RPC_PORT: "4202"
      LISTENING_PORT: "3333"
      INSTANCE_NAME: "zq2-devnet-validator-ase1-1-a6d2"
      CONTACT_DETAILS: "devops@zilliqa.com"
      WS_SERVER: "ws://198.51.100.10:3000"
      WS_SECRET: "mysecret"
      VERBOSITY: "2"
    container_name: client1
    build:
      context: .
      dockerfile: Dockerfile.zilliqa
    image: zilstats-client:latest
    networks:
      testnet:
        ipv4_address: 198.51.100.51

  client2:
    depends_on:
      - dashboard
      #- node0
    environment:
      RPC_HOST: zq2-devnet-validator-ase1-2-a6d2.zq2.dev #"198.51.100.103"
      RPC_PORT: "4202"
      LISTENING_PORT: "3333"
      INSTANCE_NAME: "zq2-devnet-validator-ase1-2-a6d2"
      CONTACT_DETAILS: "devops@zilliqa.com"
      WS_SERVER: "ws://198.51.100.10:3000"
      WS_SECRET: "mysecret"
      VERBOSITY: "2"
    container_name: client2
    build:
      context: .
      dockerfile: Dockerfile.zilliqa
    image: zilstats-client:latest
    networks:
      testnet:
        ipv4_address: 198.51.100.52

  client3:
    depends_on:
      - dashboard
      #- node0
    environment:
      RPC_HOST: zq2-devnet-validator-ase1-3-a6d2.zq2.dev #"198.51.100.103"
      RPC_PORT: "4202"
      LISTENING_PORT: "3333"
      INSTANCE_NAME: "zq2-devnet-validator-ase1-3-a6d2"
      CONTACT_DETAILS: "devops@zilliqa.com"
      WS_SERVER: "ws://198.51.100.10:3000"
      WS_SECRET: "mysecret"
      VERBOSITY: "2"
    container_name: client3
    build:
      context: .
      dockerfile: Dockerfile.zilliqa
    image: zilstats-client:latest
    networks:
      testnet:
        ipv4_address: 198.51.100.53

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 198.51.100.0/24
          gateway: 198.51.100.1
